title: EDII-Exercices
description: Exercises of 1 to 8
baseurl: '/'
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - jekyll-default-layout
navigation:
  - text: Documentation
    internal: true
    url: ./docs